#+title: Progetto NNDL traccia 7
#+author: Antonio Petrillo

* Traccia 7 (Medium difficultry)
Consider the raw images from the MNIST dataset as input.
This is a classification problem with C classes, where C= 10.
Extract a global dataset of N pairs (at least 10,000).
Use resilient backpropagation (RProp) as the weight update algorithm, with a neural network having a single layer of internal nodes.
Select the model hyperparameters, i.e., the RProp parameters (η+ and η-) and the number of internal nodes, based on a k-fold cross-validation approach (e.g., k= 10).
Compare the classical “grid” approach with the “random” approach (J. Bergstra, Y. Bengio, Random search for hyper-parameter optimization, 2012) for hyperparameter search.
Select and keep all other parameters constant, such as activation functions.
If necessary, due to computational time and memory constraints, you can reduce the dimensions of the raw MNIST dataset images (e.g., using the imresize function in MATLAB).
* Project setup
Di seguito lo script bash per creare il  [[https://docs.python.org/3/library/venv.html][virtual environment]] (venv) per il progetto
#+begin_src bash :tangle setup.sh
#!/usr/bin/env python
python -m venv venv

source ./venv/bin/activate

pip install -r requirements.txt
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
#+end_src
** Requirements
Di seguito la lista delle dipendenze per eseguire il progetto:
#+begin_src txt :tangle requirements.txt
numpy
scikit-learn
matplotlib
#+end_src

** Note
Pytorch va installato esternamente da [[https://packaging.python.org/en/latest/tutorials/installing-packages/][pip]].
Il comando presente nello script è preso direttamente dal sito di [[https://pytorch.org/get-started/locally/][pytorch]].
